# Generated by Django 4.1.2 on 2022-10-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="last_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
